version: "3.8"

services:
  mysql-account-manager:
    container_name: mysql-account-manager
    image: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account_schema
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  account-manager:
    container_name: account-manager
    image: mrcatta/ckb-account-manager
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-account-manager:3306/account_schema
    ports:
      - "8086:8086"
    restart: always

  mail-service:
    container_name: mail-service
    image: mrcatta/ckb-mail-service
    ports:
      - "8085:8085"
