name: Build and Deploy

on:
  workflow_dispatch:
    pull_request:
      branches:
        - main
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: account_schema
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: root
        ports:
          - 6306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run tests and package the application
        run: mvn clean package
        working-directory: code/

