name: Run unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - integration-tests
  pull_request:
    branches:
      - integration_tests

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run all unit tests
        run: mvn verify
        working-directory: code/
